//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "GridContent.xaml.h"

void ::UWPPenAppDraft::GridContent::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///GridContent.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::UWPPenAppDraft::GridContent::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Page^>(element1))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::UWPPenAppDraft::GridContent::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&GridContent::Page_Loaded);
            }
            break;
        case 2:
            {
                this->PageGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->PageGrid))->DragOver += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::UWPPenAppDraft::GridContent::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&GridContent::PageGrid_DragOver);
                (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->PageGrid))->Drop += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::UWPPenAppDraft::GridContent::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&GridContent::PageGrid_Drop);
                (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->PageGrid))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::UWPPenAppDraft::GridContent::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GridContent::PageGrid_PointerEntered);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::UWPPenAppDraft::GridContent::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


